/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-03 10:55:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import login.repository.impl.FileUserRepository;
import login.model.User;

public final class front_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1746268653191L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1746263984434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("login.repository.impl.FileUserRepository");
    _jspx_imports_classes.add("login.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

    // Set no-cache headers
    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
    response.setHeader("Pragma", "no-cache");
    response.setDateHeader("Expires", 0);

    // Additional logout handling
    if ("true".equals(request.getParameter("logout"))) {
        // Extra protection - invalidate session again if somehow still exists
        HttpSession session1 = request.getSession(false);
        if (session1 != null) {
            session1.invalidate();
        }
    }

      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SMART CARZONE-Second hand car sale</title>\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

  // Get user from session
  String userEmail = (String) session.getAttribute("userEmail");
  User currentUser = null;

  if (userEmail != null && !userEmail.isEmpty()) {
    try {
      FileUserRepository userRepo = new FileUserRepository();
      currentUser = userRepo.getUserByEmail(userEmail);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <img src=\"images/logo1.jpg\" alt=\"SMART CARZONE Logo\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"nav-links\">\r\n");
      out.write("    <a href=\"front.jsp\"><b>HOME</b></a>\r\n");
      out.write("    <a href=\"Buynow.jsp\"><b>BUY NOW</b></a>\r\n");
      out.write("    <a href=\"sell.jsp\"><b>SELL</b></a>\r\n");
      out.write("    <a href=\"aboutus.jsp\"><b>ABOUT US</b></a>\r\n");
      out.write("    <a href=\"contactus.jsp\"><b>CONTACT US</b></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"search-bar\">\r\n");
      out.write("    <input type=\"text\" placeholder=\"Search\">\r\n");
      out.write("    <button class=\"beautiful-button\">Search</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("  <div class=\"welcome-message\">\r\n");
      out.write("    <div>Welcome,</div>\r\n");
      out.write("    <div>");
      out.print( currentUser.getFullName() );
      out.write("!</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"user-profile\">\r\n");
      out.write("    <div class=\"profile-container\">\r\n");
      out.write("      <div class=\"profile-dropdown\">\r\n");
      out.write("        <button class=\"profile-button\" id=\"profileButton\">\r\n");
      out.write("          <img src=\"images/profile-user.png\" alt=\"Profile\" id=\"profileImage\">\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"dropdown-content\" id=\"profileDropdown\">\r\n");
      out.write("          <div class=\"user-info\">\r\n");
      out.write("            <span id=\"userName\">");
      out.print( currentUser.getFullName() );
      out.write("</span>\r\n");
      out.write("            <span id=\"userEmail\">");
      out.print( currentUser.getEmail() );
      out.write("</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"profile.jsp\" class=\"dropdown-option\">\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path d=\"M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            Edit Profile\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"#\" class=\"logout-button\" id=\"logoutButton\">\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path fill-rule=\"evenodd\" d=\"M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z\"/>\r\n");
      out.write("              <path fill-rule=\"evenodd\" d=\"M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            Logout\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 } else { 
      out.write("\r\n");
      out.write("  <div class=\"auth-buttons\">\r\n");
      out.write("    <a href=\"signin.jsp\" class=\"beautiful-button signin-button\">Sign In</a>\r\n");
      out.write("    <a href=\"register.jsp\" class=\"beautiful-button signup-button\">Sign Up</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<script src=\"js/dashboard.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Hero Section -->\r\n");
      out.write("<div class=\"hero-section\">\r\n");
      out.write("    <div class=\"hero-text\">\r\n");
      out.write("        <h1><b>No More Dreaming, Start Driving - Your Perfect Car is Here!</b></h1>\r\n");
      out.write("        <p>Discover unbeatable value and quality with our carefully inspected secondhand cars. Experience the freedom of driving a reliable vehicle without breaking the bank.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hero-image\">\r\n");
      out.write("        <img src=\"images/BN-CIVIC.jpg\" alt=\"Hero Image\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel Section -->\r\n");
      out.write("<div class=\"carousel-container\">\r\n");
      out.write("    <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <img src=\"images/Car%20Sale%20-%20Made%20with%20PosterMyWall.jpg\" class=\"d-block w-100\" alt=\"Car Sale\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"images/Luxury%20Car%20Deals%20-%20Made%20with%20PosterMyWall.jpg\" class=\"d-block w-100\" alt=\"Luxury Cars\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"images/Car%20Promo%20Banner%20-%20Made%20with%20PosterMyWall.jpg\" class=\"d-block w-100\" alt=\"Car Promo\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Indicators -->\r\n");
      out.write("        <div class=\"carousel-indicators\">\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation arrows -->\r\n");
      out.write("        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Certification Section -->\r\n");
      out.write("<div class=\"certification-section\">\r\n");
      out.write("    <div class=\"certification-text\">\r\n");
      out.write("        <h2><b>Certified Cars You Can Trust</b></h2>\r\n");
      out.write("        <p>Our cars undergo rigorous inspections to ensure top-notch quality and reliability. Each vehicle comes with a certification, giving you peace of mind with every purchase.</p>\r\n");
      out.write("        <button class=\"beautiful-button\">Learn More</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"certification-image\">\r\n");
      out.write("        <img src=\"images/thumbnail_large-1.jpg\" alt=\"Certified Cars Image\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Features Section -->\r\n");
      out.write("<div class=\"features-section\">\r\n");
      out.write("    <div class=\"features-left\">\r\n");
      out.write("        <h2><b>Discover Our Exceptional Features for a Seamless Car Buying Experience</b></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"features-right\">\r\n");
      out.write("        <p>We offer flexible financing options to fit your budget, ensuring you drive away in your dream car. Our comprehensive warranty provides peace of mind, covering essential components for your protection. Enjoy our dedicated after-sales service, designed to assist you long after your purchase.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Services Section -->\r\n");
      out.write("<div class=\"services-section\">\r\n");
      out.write("    <div class=\"services-left\">\r\n");
      out.write("        <h2><b>Comprehensive Services for Your Vehicle Needs</b></h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"services-right\">\r\n");
      out.write("        <p>We offer a seamless trade-in process to help you upgrade your vehicle effortlessly. Our financing options are flexible, making it easier for you to drive away in your dream car. Plus, we provide detailed vehicle history reports to ensure transparency and peace of mind.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- CTA Section -->\r\n");
      out.write("<section class=\"cta\">\r\n");
      out.write("    <a href=\"valuation.jsp\" class=\"rounded-btn valuation-btn\">Car Valuation</a>\r\n");
      out.write("    <a href=\"createad.jsp\" class=\"rounded-btn freead-btn\">Create Free Ad</a>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Features Grid -->\r\n");
      out.write("<section class=\"features\">\r\n");
      out.write("    <div class=\"feature\">\r\n");
      out.write("        <img src=\"images/finance1.jpg\" alt=\"Car 1\">\r\n");
      out.write("        <h3>Flexible Financing Options</h3>\r\n");
      out.write("        <p>Get the best rates and terms that will pass financial situations.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"feature\">\r\n");
      out.write("        <img src=\"images/10-year-warranty.jpg\" alt=\"Car 2\">\r\n");
      out.write("        <h3>Extended Warranty</h3>\r\n");
      out.write("        <p>Our warranty covers critical arrangements, resulting your investment is safeguarded.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"feature\">\r\n");
      out.write("        <img src=\"images/aftersale.jpg\" alt=\"Car 3\">\r\n");
      out.write("        <h3>Dedicated After-Sales Service</h3>\r\n");
      out.write("        <p>Our team is here to help you with my questions or concerns.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Reviews Section -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reviews.css\">\r\n");
      out.write("<section class=\"reviews\">\r\n");
      out.write("    <div class=\"section-title\">\r\n");
      out.write("        <h2>What Our Customers Say</h2>\r\n");
      out.write("        <div class=\"underline\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"review-slider\">\r\n");
      out.write("        <div class=\"review-track\">\r\n");
      out.write("            <!-- Review 1 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/men/32.jpg\" alt=\"John D.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"Found my perfect car at SMART CARZONE! The buying process was smooth and transparent. Got a great deal on a certified pre-owned vehicle.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">John D.</h4>\r\n");
      out.write("                <p class=\"review-position\">Business Owner</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 2 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/women/44.jpg\" alt=\"Sarah M.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"Excellent customer service! The team helped me find a reliable family SUV within my budget. The 360° virtual tour was incredibly helpful.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Sarah M.</h4>\r\n");
      out.write("                <p class=\"review-position\">Marketing Director</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 3 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/men/67.jpg\" alt=\"Michael T.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"Sold my car through SMART CARZONE and got 20% more than other offers. The process was quick and hassle-free. Highly recommend!\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Michael T.</h4>\r\n");
      out.write("                <p class=\"review-position\">Software Engineer</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 4 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/women/28.jpg\" alt=\"Emily R.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"As a first-time buyer, I was nervous, but the team guided me through every step. Love my car and the 7-day return policy gave me peace of mind.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Emily R.</h4>\r\n");
      out.write("                <p class=\"review-position\">Teacher</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 5 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/men/52.jpg\" alt=\"David L.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"The mobile app made car shopping so easy! Compared models, got financing approval, and scheduled test drives all from my phone.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">David L.</h4>\r\n");
      out.write("                <p class=\"review-position\">Financial Analyst</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 6 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/women/65.jpg\" alt=\"Jennifer K.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"The certified pre-owned program is fantastic. The extended warranty and thorough inspection made me feel confident in my purchase.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Jennifer K.</h4>\r\n");
      out.write("                <p class=\"review-position\">Nurse</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 7 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/men/22.jpg\" alt=\"Robert P.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"Third car I've bought from SMART CARZONE. Their loyalty program has real benefits, and they remember my preferences each time.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Robert P.</h4>\r\n");
      out.write("                <p class=\"review-position\">Sales Manager</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 8 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/women/33.jpg\" alt=\"Lisa W.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"The financing options were the best I found. Low interest rate and flexible terms made my dream car affordable.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Lisa W.</h4>\r\n");
      out.write("                <p class=\"review-position\">Graphic Designer</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 9 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/men/45.jpg\" alt=\"James B.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"The vehicle history reports are comprehensive. I knew exactly what I was getting. Their after-sales support is exceptional too.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">James B.</h4>\r\n");
      out.write("                <p class=\"review-position\">IT Consultant</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Review 10 -->\r\n");
      out.write("            <div class=\"review-card\">\r\n");
      out.write("                <img src=\"https://randomuser.me/api/portraits/women/50.jpg\" alt=\"Amanda S.\" class=\"profile-img\">\r\n");
      out.write("                <div class=\"stars\">★★★★★</div>\r\n");
      out.write("                <p class=\"review-text\">\"Fixed a minor issue I noticed after purchase immediately at no cost. Their commitment to customer satisfaction is impressive.\"</p>\r\n");
      out.write("                <h4 class=\"review-author\">Amanda S.</h4>\r\n");
      out.write("                <p class=\"review-position\">Small Business Owner</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation Arrows -->\r\n");
      out.write("        <div class=\"slider-nav\">\r\n");
      out.write("            <button id=\"prevBtn\" disabled><i class='bx bx-chevron-left'></i></button>\r\n");
      out.write("            <button id=\"nextBtn\"><i class='bx bx-chevron-right'></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Dots Indicators -->\r\n");
      out.write("    <div class=\"slider-dots\" id=\"sliderDots\"></div>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"js/reviews.js\"></script>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("        <div class=\"footer-container\">\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>INFORMATION</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"terms.jsp\">Terms of Service</a></li>\r\n");
      out.write("                    <li><a href=\"privacy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("                    <li><a href=\"contactus.jsp\">Contact Us</a></li>\r\n");
      out.write("                    <li><a href=\"aboutus.jsp\">About Us</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>SELL YOUR CAR</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">Advertise for free</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Advert promotions</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Car valuation</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>CONTACT US</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><i class='bx bx-map'></i>130B, Pannipittya Road,<br>Battaramulla, Sri Lanka.</li>\r\n");
      out.write("                    <li><i class='bx bx-phone'></i>Phone: 011 1234 500</li>\r\n");
      out.write("                    <li><i class='bx bx-printer'></i>Fax: 011 1234 501</li>\r\n");
      out.write("                    <li><i class='bx bx-mobile-alt'></i>Hotline: 071 2345 678</li>\r\n");
      out.write("                    <li><i class='bx bx-envelope'></i>Email: info@SMARTCARZONE.lk</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"social-media\">\r\n");
      out.write("            <a href=\"#\" aria-label=\"Facebook\"><i class='bx bxl-facebook'></i></a>\r\n");
      out.write("            <a href=\"#\" aria-label=\"Instagram\"><i class='bx bxl-instagram'></i></a>\r\n");
      out.write("            <a href=\"#\" aria-label=\"LinkedIn\"><i class='bx bxl-linkedin'></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom\">\r\n");
      out.write("            © 2025 SMART CARZONE\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
