/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-03 11:39:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import login.repository.impl.FileUserRepository;
import login.model.User;

public final class signin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1746268653191L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1746263984434L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("login.repository.impl.FileUserRepository");
    _jspx_imports_classes.add("login.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sign In - SMART CARZONE</title>\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Reuse the same navbar from your main page -->\r\n");
      out.write('\r');
      out.write('\n');

  // Get user from session
  String userEmail = (String) session.getAttribute("userEmail");
  User currentUser = null;

  if (userEmail != null && !userEmail.isEmpty()) {
    try {
      FileUserRepository userRepo = new FileUserRepository();
      currentUser = userRepo.getUserByEmail(userEmail);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("<nav class=\"navbar\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <img src=\"images/logo1.jpg\" alt=\"SMART CARZONE Logo\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"nav-links\">\r\n");
      out.write("    <a href=\"front.jsp\"><b>HOME</b></a>\r\n");
      out.write("    <a href=\"Buynow.jsp\"><b>BUY NOW</b></a>\r\n");
      out.write("    <a href=\"sell.jsp\"><b>SELL</b></a>\r\n");
      out.write("    <a href=\"aboutus.jsp\"><b>ABOUT US</b></a>\r\n");
      out.write("    <a href=\"contactus.jsp\"><b>CONTACT US</b></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"search-bar\">\r\n");
      out.write("    <input type=\"text\" placeholder=\"Search\">\r\n");
      out.write("    <button class=\"beautiful-button\">Search</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("  <div class=\"welcome-message\">\r\n");
      out.write("    <div>Welcome,</div>\r\n");
      out.write("    <div>");
      out.print( currentUser.getFullName() );
      out.write("!</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"user-profile\">\r\n");
      out.write("    <div class=\"profile-container\">\r\n");
      out.write("      <div class=\"profile-dropdown\">\r\n");
      out.write("        <button class=\"profile-button\" id=\"profileButton\">\r\n");
      out.write("          <img src=\"images/profile-user.png\" alt=\"Profile\" id=\"profileImage\">\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"dropdown-content\" id=\"profileDropdown\">\r\n");
      out.write("          <div class=\"user-info\">\r\n");
      out.write("            <span id=\"userName\">");
      out.print( currentUser.getFullName() );
      out.write("</span>\r\n");
      out.write("            <span id=\"userEmail\">");
      out.print( currentUser.getEmail() );
      out.write("</span>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"profile.jsp\" class=\"dropdown-option\">\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path d=\"M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            Edit Profile\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"#\" class=\"logout-button\" id=\"logoutButton\">\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" viewBox=\"0 0 16 16\">\r\n");
      out.write("              <path fill-rule=\"evenodd\" d=\"M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z\"/>\r\n");
      out.write("              <path fill-rule=\"evenodd\" d=\"M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z\"/>\r\n");
      out.write("            </svg>\r\n");
      out.write("            Logout\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 } else { 
      out.write("\r\n");
      out.write("  <div class=\"auth-buttons\">\r\n");
      out.write("    <a href=\"signin.jsp\" class=\"beautiful-button signin-button\">Sign In</a>\r\n");
      out.write("    <a href=\"register.jsp\" class=\"beautiful-button signup-button\">Sign Up</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("<script src=\"js/dashboard.js\"></script>");
      out.write("\r\n");
      out.write("<!-- Sign In Hero Section -->\r\n");
      out.write("<section class=\"signin-hero\">\r\n");
      out.write("    <h1>Welcome Back to SMART CARZONE</h1>\r\n");
      out.write("    <p>Sign in to access your account and continue your car buying or selling journey</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Sign In Form Container -->\r\n");
      out.write("<div class=\"signin-container\">\r\n");
      out.write("    <div class=\"signin-header\">\r\n");
      out.write("        <h2>Sign In to Your Account</h2>\r\n");
      out.write("        <p>Enter your credentials to access your personalized dashboard</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <form id=\"signinForm\" action=\"auth\" method=\"POST\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"login\">\r\n");
      out.write("        <!-- Error Message Display -->\r\n");
      out.write("        <div class=\"container mt-3\">\r\n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger alert-dismissible fade show\">\r\n");
      out.write("                ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (request.getAttribute("success") != null) { 
      out.write("\r\n");
      out.write("        <div class=\"alert alert-success alert-dismissible fade show\">\r\n");
      out.write("            ");
      out.print( request.getAttribute("success") );
      out.write("\r\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <!-- Email Field - Fixed spacing -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"email\">Email Address</label>\r\n");
      out.write("            <div class=\"input-with-icon\">\r\n");
      out.write("                <i class='bx bx-envelope input-icon'></i>\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Enter your email address\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Password Field  -->\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("            <label for=\"password\">Password</label>\r\n");
      out.write("            <div class=\"input-with-icon password-input\">\r\n");
      out.write("                <i class='bx bx-lock-alt input-icon'></i>\r\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Enter your password\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Remember Me & Forgot Password -->\r\n");
      out.write("        <div class=\"remember-forgot\">\r\n");
      out.write("            <div class=\"remember-me\">\r\n");
      out.write("                <input type=\"checkbox\" id=\"remember\" name=\"remember\">\r\n");
      out.write("                <label for=\"remember\">Remember me</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"forgot-password\">\r\n");
      out.write("                <a href=\"forgot-password.jsp\">Forgot password?</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sign In Button -->\r\n");
      out.write("        <button type=\"submit\" class=\"signin-btn\">Sign In</button>\r\n");
      out.write("\r\n");
      out.write("        <!-- Divider -->\r\n");
      out.write("        <div class=\"divider\">or continue with</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Social Login Options -->\r\n");
      out.write("        <div class=\"social-login\">\r\n");
      out.write("            <a href=\"#\" class=\"social-btn\" title=\"Sign in with Google\">\r\n");
      out.write("                <i class='bx bxl-google'></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"social-btn\" title=\"Sign in with Facebook\">\r\n");
      out.write("                <i class='bx bxl-facebook'></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#\" class=\"social-btn\" title=\"Sign in with LinkedIn\">\r\n");
      out.write("                <i class='bx bxl-linkedin'></i>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Sign Up Link -->\r\n");
      out.write("        <div class=\"signup-link\">\r\n");
      out.write("            Don't have an account? <a href=\"register.jsp\">Create one now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <!-- Security Notice -->\r\n");
      out.write("    <div class=\"security-notice\">\r\n");
      out.write("        <i class='bx bx-shield-alt-2'></i>\r\n");
      out.write("        Your information is protected by 256-bit SSL encryption\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Reuse the same footer from your main page -->\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("        <div class=\"footer-container\">\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>INFORMATION</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"terms.jsp\">Terms of Service</a></li>\r\n");
      out.write("                    <li><a href=\"privacy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("                    <li><a href=\"contactus.jsp\">Contact Us</a></li>\r\n");
      out.write("                    <li><a href=\"aboutus.jsp\">About Us</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>SELL YOUR CAR</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#\">Advertise for free</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Advert promotions</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Car valuation</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>CONTACT US</h3>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><i class='bx bx-map'></i>130B, Pannipittya Road,<br>Battaramulla, Sri Lanka.</li>\r\n");
      out.write("                    <li><i class='bx bx-phone'></i>Phone: 011 1234 500</li>\r\n");
      out.write("                    <li><i class='bx bx-printer'></i>Fax: 011 1234 501</li>\r\n");
      out.write("                    <li><i class='bx bx-mobile-alt'></i>Hotline: 071 2345 678</li>\r\n");
      out.write("                    <li><i class='bx bx-envelope'></i>Email: info@SMARTCARZONE.lk</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"social-media\">\r\n");
      out.write("            <a href=\"#\" aria-label=\"Facebook\"><i class='bx bxl-facebook'></i></a>\r\n");
      out.write("            <a href=\"#\" aria-label=\"Instagram\"><i class='bx bxl-instagram'></i></a>\r\n");
      out.write("            <a href=\"#\" aria-label=\"LinkedIn\"><i class='bx bxl-linkedin'></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom\">\r\n");
      out.write("            © 2025 SMART CARZONE\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
